# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf512c25cfbb5da095d577e0129889060a0ac5e2654948668434b4338d28f92b0a2dc2a3ec4b54be1b91d0f6b8980d832f87e2fcb4b87f7d9973cfaadacc9e0e

test:
  secret_key_base: 934320aefc0c1a0329de449f0dcc99099f193c0679aef8b10b010a50a5c66d013693a6377942de54b52b7c33f6ddce3d76232766bcede697522ac107a9aab65c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
